fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

pfe_user:
    resource: "@PFEUserBundle/Resources/config/routing.yml"
    prefix:   /u

pfe_dash:
    resource: "@PFEDashBundle/Resources/config/routing.yml"
    prefix:   /