pfe_dash_remarque:
    resource: "@PFEDashBundle/Resources/config/routing/remarque.yml"
    prefix:   /remarque

pfe_dash_equipement:
    resource: "@PFEDashBundle/Resources/config/routing/equipement.yml"
    prefix:   /equipement

pfe_dash_espace:
    resource: "@PFEDashBundle/Resources/config/routing/espace.yml"
    prefix:   /espace

pfe_dash_internet:
    resource: "@PFEDashBundle/Resources/config/routing/internet.yml"
    prefix:   /internet

pfe_dash_socialmedia:
    resource: "@PFEDashBundle/Resources/config/routing/socialmedia.yml"
    prefix:   /saisi/socialmedia

# default controller
pfe_dash_homepage:
    path:     /hello/{name}
    defaults: { _controller: PFEDashBundle:Default:index }

# bib controller
pfe_dash_bib_presentation:
    path:     /presentation/{id}
    defaults: { _controller: PFEDashBundle:Bib:presentation }
    requirements:
        id: "[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}"

pfe_dash_bib_espaces:
    path:     /espaces
    defaults: { _controller: PFEDashBundle:Bib:espaces }

pfe_dash_bib_equipements:
    path:     /equipements
    defaults: { _controller: PFEDashBundle:Bib:equipements }

pfe_dash_bib_fonds:
    path:     /fonds
    defaults: { _controller: PFEDashBundle:Bib:fonds }

pfe_dash_bib_catalogues:
    path:     /catalogues
    defaults: { _controller: PFEDashBundle:Bib:catalogues }

pfe_dash_bib_prets:
    path:     /prets
    defaults: { _controller: PFEDashBundle:Bib:prets }

pfe_dash_bib_animations:
    path:     /animations
    defaults: { _controller: PFEDashBundle:Bib:animations }

pfe_dash_bib_remarques:
    path:     /remarques
    defaults: { _controller: PFEDashBundle:Bib:remarques }

pfe_dash_bib_menu:
    path:     /menu
    defaults: { _controller: PFEDashBundle:Bib:menu }

pfe_dash_bib_province:
    path:     /province/{id}
    defaults: { _controller: PFEDashBundle:Bib:province }
    requirements:
        id: "[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}"