bibliotheque:
    path:     /
    defaults: { _controller: "PFEDashBundle:Bibliotheque:index" }

bibliotheque_show:
    path:     /{id}/show
    defaults: { _controller: "PFEDashBundle:Bibliotheque:show" }

bibliotheque_new:
    path:     /new
    defaults: { _controller: "PFEDashBundle:Bibliotheque:new" }

bibliotheque_create:
    path:     /create
    defaults: { _controller: "PFEDashBundle:Bibliotheque:create" }
    methods:  POST

bibliotheque_edit:
    path:     /{id}/edit
    defaults: { _controller: "PFEDashBundle:Bibliotheque:edit" }

bibliotheque_update:
    path:     /{id}/update
    defaults: { _controller: "PFEDashBundle:Bibliotheque:update" }
    methods:  [POST, PUT]

bibliotheque_delete:
    path:     /{id}/delete
    defaults: { _controller: "PFEDashBundle:Bibliotheque:delete" }
    methods:  [POST, DELETE]
