equipement:
    path:     /
    defaults: { _controller: "PFEDashBundle:Equipement:index" }

equipement_show:
    path:     /{id}/show
    defaults: { _controller: "PFEDashBundle:Equipement:show" }

equipement_new:
    path:     /new
    defaults: { _controller: "PFEDashBundle:Equipement:new" }

equipement_create:
    path:     /create
    defaults: { _controller: "PFEDashBundle:Equipement:create" }
    methods:  POST

equipement_edit:
    path:     /{id}/edit
    defaults: { _controller: "PFEDashBundle:Equipement:edit" }

equipement_update:
    path:     /{id}/update
    defaults: { _controller: "PFEDashBundle:Equipement:update" }
    methods:  [POST, PUT]

equipement_delete:
    path:     /{id}/delete
    defaults: { _controller: "PFEDashBundle:Equipement:delete" }
    methods:  [POST, DELETE]
