espace:
    path:     /
    defaults: { _controller: "PFEDashBundle:Espace:index" }

espace_show:
    path:     /{id}/show
    defaults: { _controller: "PFEDashBundle:Espace:show" }

espace_new:
    path:     /new
    defaults: { _controller: "PFEDashBundle:Espace:new" }

espace_create:
    path:     /create
    defaults: { _controller: "PFEDashBundle:Espace:create" }
    methods:  POST

espace_edit:
    path:     /{id}/edit
    defaults: { _controller: "PFEDashBundle:Espace:edit" }

espace_update:
    path:     /{id}/update
    defaults: { _controller: "PFEDashBundle:Espace:update" }
    methods:  [POST, PUT]

espace_delete:
    path:     /{id}/delete
    defaults: { _controller: "PFEDashBundle:Espace:delete" }
    methods:  [POST, DELETE]
