remarque:
    path:     /list
    defaults: { _controller: "PFEDashBundle:Remarque:index" }

remarque_show:
    path:     /{id}/show
    defaults: { _controller: "PFEDashBundle:Remarque:show" }

remarque_new:
    path:     /new
    defaults: { _controller: "PFEDashBundle:Remarque:new" }

remarque_create:
    path:     /create
    defaults: { _controller: "PFEDashBundle:Remarque:create" }
    methods:  POST

remarque_edit:
    path:     /{id}/edit
    defaults: { _controller: "PFEDashBundle:Remarque:edit" }

remarque_update:
    path:     /{id}/update
    defaults: { _controller: "PFEDashBundle:Remarque:update" }
    methods:  [POST, PUT]

remarque_delete:
    path:     /{id}/delete
    defaults: { _controller: "PFEDashBundle:Remarque:delete" }
    methods:  [POST, DELETE]
